In [6]:
from HMM_Functions import *
from Filtering_Function import filtering
from matplotlib import cm, pyplot as plt
import seaborn
from matplotlib.dates import YearLocator, MonthLocator, DayLocator
import pandas as pd
import numpy as np
from datetime import datetime

In [7]:
file_name = 'fwonk.us.txt'
df_fwonk_stock = get_stock_data(file_name)
df_fwonk_stock = df_fwonk_stock[-30:]
df_fwonk_stock = df_fwonk_stock.reset_index()
df_fwonk_stock

    index  Close       Date     High     Low    Open OpenInt   Volume
0     801  37.91 2017-10-02    38.21   37.46      38       0  1194803
1     802  39.08 2017-10-03     39.1   37.79   38.17       0  3393734
2     803  39.88 2017-10-04    39.97   38.76   39.01       0  2267635
3     804  40.72 2017-10-05  41.1287   39.95   39.99       0  4040042
4     805  40.45 2017-10-06    40.83  40.085   40.75       0  3091133
5     806  40.16 2017-10-09     40.6    40.1   40.48       0  1626664
6     807  39.58 2017-10-10   40.315   39.51   40.13       0   584055
7     808  39.23 2017-10-11    39.61   39.07   39.61       0  1571951
8     809  39.64 2017-10-12    39.65   38.59   39.08       0  1051405
9     810   39.5 2017-10-13     39.8   39.27   39.27       0   543815
10    811  40.04 2017-10-16     40.1   39.45   39.58       0  1002921
11    812  40.12 2017-10-17    40.67   39.78   40.67       0   757107
12    813  40.07 2017-10-18    40.31   39.95   40.12       0   746266
13    814  39.98 2017-10-19    40.27   39.46   40.25       0   766037
14    815  40.42 2017-10-20    41.14   39.77   40.31       0  1544789
15    816  39.19 2017-10-23    40.42   39.08    40.3       0  1187413
16    817     39 2017-10-24     39.8   38.91   39.25       0  2828334
17    818     39 2017-10-25    39.14   38.35    38.9       0   934960
18    819  37.63 2017-10-26    39.11   37.28   38.85       0  1725722
19    820  38.49 2017-10-27    38.97   37.55  37.715       0  1116504
20    821  38.68 2017-10-30     38.8      38   38.52       0   716218
21    822  38.14 2017-10-31    38.63   37.82   38.62       0  1274876
22    823  38.46 2017-11-01    38.76   38.05   38.19       0   936134
23    824  38.05 2017-11-02     38.7   37.88   38.34       0  1180073
24    825  37.87 2017-11-03    38.54   37.29   37.99       0  1758133
25    826  38.73 2017-11-06     38.9   37.85   37.89       0   720954
26    827  38.01 2017-11-07  39.1999  37.975   38.71       0   845409
27    828  37.55 2017-11-08    38.23   37.44   38.06       0  1520987
28    829  37.42 2017-11-09    39.12   36.82   37.25       0  2119373
29    830  37.45 2017-11-10     37.9   37.11   37.11       0  2300982

In [8]:
# Get data and initialize
df_emission = get_emission(df_fwonk_stock)
emission = df_emission['Emission'][1:]
emission_list = emission.tolist()

tpm = [[0.3, 0.3, 0.2, 0.1, 0.05, 0.05],
       [0.25, 0.3, 0.25, 0.1, 0.05, 0.05],
       [0.1, 0.1, 0.3, 0.2, 0.2, 0.1],
       [0.1, 0.1, 0.2, 0.3, 0.2, 0.1],
       [0.05, 0.05, 0.1, 0.25, 0.3, 0.25],
       [0.05, 0.05, 0.1, 0.2, 0.3, 0.3]]

#tpm = create_TPM(6)

epm = create_EPM(6, 2)
NUM_STATES = 6

pi = [.2, .1, .1, .2, .1, .1]

In [9]:
tpm, epm = baum_welch(tpm, epm, pi, emission_list)

KeyboardInterrupt:

In [ ]:
tpm

In [ ]:
epm

In [ ]:
states_path = viterbi(tpm, epm, pi, emission_list)

In [ ]:
updated_stock_df = add_hidden_states_to_df(df_emission, states_path)
updated_stock_df

In [ ]:
graph_hidden_states(updated_stock_df, states_path)

In [ ]:
print(emission_list)

In [ ]:
filtering(tpm, epm, emission_list, pi)